### ISSUE TITLE
There was a problem installing dependencies using pip

### ISSUE THREAD

**Issue by Nanawwa** [PigBotFramework/main#1]
![image](https://user-images.githubusercontent.com/57826838/209486084-6053c3f2-b355-4f87-8e87-99f8feb015a5.png)
No such file or directory: '/pbf/chatterbot/ChatterBot' 
It seems that this file is not provided in the repository？

**Comment by Gingmzmzx** [comment]
抱歉没想到这个问题，  
这个是我本地魔改的一个ChatterBot，您可以手动安装Chatterbot  
```bash
pip install chatterbot
```
然后忽略rms.txt中的那一行就可以了
