### ISSUE TITLE
建议全部自己写一遍

### ISSUE THREAD

**Issue by yinghanwen** [PigBotFramework/main#2]
fastapi已经有很棒的机器人框架nonebot了
建议换个驱动框架重新写一遍

**Comment by Gingmzmzx** [comment]
猪比之前并不是用的`fastapi`，而是`flask`  
并且，猪比有其他的优点，比如内置了很多功能类似于自动转图片、nsfw、imageutils等  
猪比还有重要的一部分就是官网。猪比官网的功能是与猪比机器人紧密相连的。  
另外我认为，猪比的API等使用都是很便捷的，各种监听器注册也非常方便，至少自己使用是很顺手的~
